### ISSUE TITLE
[fx_importer] segfault when trying to create a DenseResourceElementsAttr with a scalar value

### ISSUE THREAD

**Issue by dan-garvey** [nod-ai/SHARK-Turbine#398]
Fix: 0d tensors should be special cased here as DenseElementsAttr not DenseResourceElementsAttr:
 https://github.com/nod-ai/SHARK-Turbine/blob/main/core/shark_turbine/importers/fx_importer.py#L932

**Comment by stellaraccident** [comment]
This was also reported by someone else a few days back but I can't remember who/where. I have not seen a patch to fix it yet.

The issue is that DenseResourceElementsAttr does not properly handle 0d tensors. While it arguably should behave better than this, it begs the question that it is the wrong thing to be doing for such a case.

The best thing to do would be to update the code listed above to special case on 1-element tensors (0d or 1d-1element) to instead generate a splat value: https://github.com/llvm/llvm-project/blob/main/mlir/lib/Bindings/Python/IRAttributes.cpp#L33

That API is more than a bit wobbly and I would recommend adding a peephole unit test for these literal conversion cases that pokes it with lasers from all sides. Here are the full upstream unit tests for it: https://github.com/llvm/llvm-project/blob/main/mlir/test/python/ir/array_attributes.py

I think if you pass `DenseElementsAttr.get(array=np_tensor, type=tensor_type)` it will do the right thing (i.e. conditional code after line 927 if the np_tensor has one element vs not). You can skip all of the memoryview mapping stuff in the 1-element case.
