### ISSUE TITLE
SDXL vae encode compilation failure

### ISSUE THREAD

**Issue by jinchen62** [nod-ai/SHARK-Turbine#449]
The compilation crashes on all backends.
vae encode mlir: https://storage.googleapis.com/shark_tank/jinchen/sdxl/vae_encode.mlir

**ROCm:**
crash backtrace: https://gist.github.com/jinchen62/e58495cc2d1adbe23c24f5ce5a3c26eb
dispatch: https://gist.github.com/jinchen62/a7976189aa4ff354c8c4f050dce1e144
command: `tools/iree-compile --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx90a --iree-rocm-link-bc=true --iree-rocm-bc-dir=/opt/rocm/amdgcn/bitcode sdxl_vae_encode_dispatch_170.mlir -o sdxl_vae_encode_dispatch_170.vmfb --mlir-print-ir-after-all 2> dump.mlir`

**CPU:**
> error: internal error: jit global source initialization order. global "hoisted_4" has no value

command: `tools/iree-compile --iree-hal-target-backends=llvm-cpu vae_encode.mlir -o vae_encode.vmfb 2> dump.txt`

**Vulkan:**
> error: failed to handle capability Matrix

dispatch: https://gist.github.com/jinchen62/df1a4c5db13b369cc4dcd4239a286572
command: `tools/iree-compile --iree-hal-target-backends=vulkan-spirv --compile-mode=hal-executable vae_encode_vulkan_dispatch_142.mlir -o vae_encode_vulkan_dispatch_142.vmfb --mlir-print-ir-after-all 2> dump.mlir`

**Comment by antiagainst** [comment]
> vae encode mlir: https://storage.googleapis.com/shark_tank/jinchen/sdxl/vae_encode.mlir

Hi @jinchen62 where did you get this model? This is not the model that we have in the playbook? Actually the VAE models for both SDXL and SDXL Turbo in the playbook compiles fine..

> dispatch: https://gist.github.com/jinchen62/a7976189aa4ff354c8c4f050dce1e144

This is a scalar dispatch. The issue is legit--it crashes the compiler. Repro command can just be `iree-compile --compile-mode=hal-executable input.mlir`. The solution would be add a basic lowering pipeline without tiling and distribution like https://github.com/openxla/iree/pull/14377. Given that I cannot reproduce the issue in VAE models I will not prioritize fixing it. It's a good isolated (starter) task for somebody else to fix anyway.

**Comment by jinchen62** [comment]
@antiagainst The VAE IRs in the playbook are VAE decode.

**Comment by monorimet** [comment]
In current playbook, vae encode and decode are separate. This issue is _not_ reproducible with the playbook artifacts because they _contain sdpfa as a torch.operator_. @jinchen62 is using mlir with sdpfa decomposed.

**Comment by antiagainst** [comment]
> In current playbook, vae encode and decode are separate. This issue is _not_ reproducible with the playbook artifacts because they _contain sdpfa as a torch.operator_. @jinchen62 is using mlir with sdpfa decomposed.

Cool I see. Thanks for the explanation!
