### ISSUE TITLE
ImageDecoder

### ISSUE THREAD

**Issue by vivekkhandelwal1** [nod-ai/SHARK-Turbine#730]
Assigned to @vinayakdsci

**Comment by ScottTodd** [comment]
Is there a plan for this one? https://onnx.ai/onnx/operators/onnx__ImageDecoder.html looks out of scope for compiler codegen to me...

> Loads and decodes and image from a file. If it can’t decode for any reason (e.g. corrupted encoded stream, invalid format, it will return an empty matrix). The following image formats are supported:
> * BMP
> * JPEG (note: Lossless JPEG support is optional)
> * JPEG2000
> * TIFF
> * PNG
> * WebP

**Comment by vinayakdsci** [comment]
@ScottTodd can't we simply treat the image as a (H,W,C) shaped tensor of uint8 values?. We would then only need to check for the pixel format.

**Comment by ScottTodd** [comment]
The op loads from encoded image files in any of those formats. Those formats are incredibly complicated and working with them is nearly always delegated to external libraries, platform APIs, or hardware decoders. This is the sort of thing that inference frameworks usually leave to higher level APIs, or include via plugins - not something that the compiler would generate code for directly.

ImageDecoder isn't even implemented in onnxruntime yet: https://github.com/microsoft/onnxruntime/issues/17593. When the op was added to ONNX in https://github.com/onnx/onnx/pull/5294, the author said "I was hoping that the ORT team will handle the implementation. It should be simple using a library such as OpenCV.". Simple... yeah, right, just take a dep on another framework that doesn't even exist on many platforms :P

**Comment by vinayakdsci** [comment]
> The op loads from encoded image files in any of those formats. Those formats are incredibly complicated and working with them is nearly always delegated to external libraries, platform APIs, or hardware decoders. This is the sort of thing that inference frameworks usually leave to higher level APIs, or include via plugins - not something that the compiler would generate code for directly.
> 
> ImageDecoder isn't even implemented in onnxruntime yet: [microsoft/onnxruntime#17593](https://github.com/microsoft/onnxruntime/issues/17593). When the op was added to ONNX in [onnx/onnx#5294](https://github.com/onnx/onnx/pull/5294), the author said "I was hoping that the ORT team will handle the implementation. It should be simple using a library such as OpenCV.". Simple... yeah, right, just take a dep on another framework that doesn't even exist on many platforms :P

Ah, my first thought regarding the implementation was that it would recieve the tensor _after_ loading the image, and not make loading that a part of the implementation at all. The user would call into the op after they had loaded the image, maybe by the use of a library like PIL. But you seem to be right here, it appears to be difficult to work with without delegating to an external library.

So what do you suggest? Is it worth a stab or not?

**Comment by ScottTodd** [comment]
If the goal is just to claim support for the op, I wouldn't bother with this one.

If the goal is to solve a specific customer request, I'd look deeper at how the op is used and find other ways to solve their problem.

**Comment by vinayakdsci** [comment]
HI @vivekkhandelwal1,  This op is almost impossible to implement without the use of external libraries to read in the supported image formats, owing to their complexity.

The following is a rough sketch of the implementation:
1. The op takes in a 1-D tensor of bytes(uint8 values) that represent the image(in one of the formats that are supported). 
2. Then it loads the image(the reference implementation uses PIL in python for this), which converts it to a tensor of shape `[height, width, num_channels]` and dimension 3. 
3. Once this has been done, an output decoded image of the same shape as the converted tensor is built based on what pixel_format was passed in.

The step (2) is unfeasible to implement without the use of an external library like OpenCV. My initial thought was that we could bypass the process of loading the image into a tensor, and leave that for the user to do, so that we would then expect a 3-D tensor as input.
However, this would make it impossible to write e2e tests, for which the onnx back end due to its shape inference would not allow a 3-D input, and a 1-D image array in one of the supported formats is expected.

What do you think is the way forward? Should we skip the e2e tests and make do with the lit tests then? Or drop support for this op altogether?

**Comment by ScottTodd** [comment]
> My initial thought was that we could bypass the process of loading the image into a tensor, and leave that for the user to do, so that we would then expect a 3-D tensor as input.

That would be changing the semantics of the op to the point that there is very little left of the original definition. If a user needs to change their program to use this toolchain, have them change their model. Don't change the semantics of an op just to claim support for it.

> Should we skip the e2e tests and make do with the lit tests then?

IDK. You can do a surface level import of the onnx op into torch-mlir and test that translation, but if no backend will be able to run the op then I don't see the point. Are there backends for torch-mlir (other than IREE) that could support this op?

**Comment by vinayakdsci** [comment]
> That would be changing the semantics of the op to the point that there is very little left of the original definition.

Yes, that is the primary point of concern, aside from the difficulties with e2e tests.
 
> Are there backends for torch-mlir (other than IREE) that could support this op?

No, none that I am aware of at the moment that would allow for an easier implementation.

The thing is, even the lit tests are reduced to just checking against the `pixel_format` and performing basic array operations independent of the file format, so much so that the op feels too much bare of useful functionality.

Still, let us also wait to hear what @vivekkhandelwal1's opinion on the matter is.
Thanks!

**Comment by vivekkhandelwal1** [comment]
> HI @vivekkhandelwal1, This op is almost impossible to implement without the use of external libraries to read in the supported image formats, owing to their complexity.
> 
> The following is a rough sketch of the implementation:
> 
> 1. The op takes in a 1-D tensor of bytes(uint8 values) that represent the image(in one of the formats that are supported).
> 2. Then it loads the image(the reference implementation uses PIL in python for this), which converts it to a tensor of shape `[height, width, num_channels]` and dimension 3.
> 3. Once this has been done, an output decoded image of the same shape as the converted tensor is built based on what pixel_format was passed in.
> 
> The step (2) is unfeasible to implement without the use of an external library like OpenCV. My initial thought was that we could bypass the process of loading the image into a tensor, and leave that for the user to do, so that we would then expect a 3-D tensor as input. However, this would make it impossible to write e2e tests, for which the onnx back end due to its shape inference would not allow a 3-D input, and a 1-D image array in one of the supported formats is expected.
> 
> What do you think is the way forward? Should we skip the e2e tests and make do with the lit tests then? Or drop support for this op altogether?

I'm not very sure, if we would ever need this op. But to claim the ONNX op support right now we can just go ahead with a lit test and skip the e2e test for now. (If required, we will revisit this op later)

**Comment by vinayakdsci** [comment]
Resolved by https://github.com/llvm/torch-mlir/pull/3478.

**Comment by vivekkhandelwal1** [comment]
Hi @vinayakdsci, since we've dropped the plan for supporting this op for now, so I'm closing the issue and the corresponding PR. If needed, we can revisit this later.
